#######################
# Theme Customization #
#######################

title: kil ye won's homepage                 # used in <title> tag & site header
author: kil ye won                      # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  단국대학교 컴퓨터공학과 재학
  
slogan: 나도몰르는대 ? 어카라고 일단씀                 # used in site header, beside title
avatar: ./i/avatar.png                       # used as portrait in site header
banner: ./i/mountains.svg                    # used as background in site header
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/okprocesser/okprocesser.github.io


# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts
  - name: About Me
    url: /about
    icon: /i/icons.svg#user
  - name: GitHub
    url: https://github.com/okprocesser
    icon: /i/icons.svg#github
    outbound: true
  - name: Contact
    scheme: kyw5289.94@gmail.com
    handle: hello
    domain: github.com
    icon: /i/icons.svg#email



#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
